Feature/tan 17 symptom selectors
wintergreenbliss/tangie pull request #9
Opened 2022-08-19 22:47 UTC by dan-kiss-dev-this

symptom selector made

2022-09-02 17:43 UTC, illepic requested changes

2022-09-02 17:43 UTC, illepic commented on components/symptomTag.tsx
> +  children?: any;
Type as `ReactNode`.

2022-09-02 17:43 UTC, illepic commented on components/symptomTag.tsx
> +  text: String;
Lower case, `String` isn't a type.

2022-09-02 17:43 UTC, illepic commented on components/symptomTag.tsx
> +  children = null,
No default `null`.

2022-09-02 17:43 UTC, illepic commented on components/symptomTag.tsx
> +  children?: any;
Not optional.

2022-09-02 17:43 UTC, illepic commented on tailwind.config.js
> +          },
Move to `blerple.300` instead.

2022-10-08 19:20 UTC, illepic requested changes

2022-10-08 19:20 UTC, illepic commented on components/selectorGroup.tsx
> +    }
Let's try and early return instead of else.

2022-10-08 19:20 UTC, illepic commented on components/symptom.tsx
> +        'bg-white-500  ': selected,
Remove double space

2022-10-08 19:20 UTC, illepic commented on components/symptom.tsx
> +    <div>{children} </div>
Extra space

2022-10-12 11:09 UTC, paabloLC commented on components/symptom.tsx
> +        'bg-white-500  ': selected,
this is done!

2022-10-18 04:41 UTC, illepic approved these changes

2022-10-18 04:41 UTC, merged